### ISSUE TITLE
Site is too small on mobile

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/gamehub#13]
responsiveness isnt broken but everything is really small

**Comment by trollfaicgaming** [comment]
try using
<meta name="viewport" content="width=device-width, initial-scale=1.0>

**Comment by ZeroIntensity** [comment]
don't know anything about how viewport works but ill try it

**Comment by trollfaicgaming** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag

**Comment by ZeroIntensity** [comment]
seems to work alright, any other issues are put onto #11
